CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(2000) NOT NULL,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created timestamp NOT NULL,
    updated timestamp NOT NULL,
    updated_by VARCHAR(5) NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    );