spring:
  application:
    name: request-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/