CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,
    created timestamp NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
    );